# -*- coding: utf-8 -*-
"""Aula3(media aluno).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Jtl2IqVkO0Yl3_tL6bPNCwbBrTfgfTaX
"""

aluno = input('digite o nome do aluno:')
n1 = float(input('digite a primeira nota:'))
n2 = float(input('digite a primeira nota:'))
n3 = float(input('digite a primeira nota:'))
media = (n1+n2+n3)/3
print(media)
if media >=7:
    situaçao = 'foi aaprovado'
elif media >=5:
     situaçao = 'ficou em recuperaçao'    
else:
    situaçao = 'reprovado'
print(f'O {aluno} foi {situaçao} com a media {media:.2f}')